### ISSUE TITLE
Could not resolve host: serverlist.piaservers.com

### ISSUE THREAD

**Issue by Hallo-457** [thrnz/docker-wireguard-pia#106]
![Screenshot (84)](https://github.com/thrnz/docker-wireguard-pia/assets/87528567/7c9ae90c-ec3e-49f5-9152-21c4e399c599)
![Screenshot (83)](https://github.com/thrnz/docker-wireguard-pia/assets/87528567/e38fe2ad-6068-473a-8b87-460b97b411b0)

like the Issue #105 
i have a second docker instance on another machine with the same docker compose and there is evereything working fine even after restart

**Comment by thrnz** [comment]
Nothing immediately comes to mind, especially if the same compose file is working on another machine.

It might be worth trying with `FIREWALL=0` set just to rule out the container actively blocking dns queries. Previously allowing loopback traffic and outgoing udp port 53 was enough for the initial dns queries, though seeing as #105 was fixed by rolling back to an earlier version of Docker engine, I wonder if something might have changed there. If it still doesn't work with the firewall disabled, then it might be something else causing the issue instead.

The 404 is likely unrelated, though it does confirm that its resolving. The full url being retrieved is https://serverlist.piaservers.net/vpninfo/servers/v6

**Comment by Hallo-457** [comment]
firewall didnt fix the issue, i didnt update anything the last days.

**Comment by Hallo-457** [comment]
i cleared that it associated with this container and now:

`Mon May  6 09:13:44 UTC 2024: Generating auth token
curl: (6) Could not resolve host: www.privateinternetaccess.com
Failed to acquire new auth token. Response:
Mon May  6 09:13:50 UTC 2024: Failed to acquire new auth token
Mon May  6 09:13:50 UTC 2024: Fatal error`

**Comment by thrnz** [comment]
It might be worth trying running something like `nslookup serverlist.piaservers.net` and/or `wget https://serverlist.piaservers.net/vpninfo/servers/v6` inside the container once it's failed just to rule out another curl specific issue (such as #92).

Apart from that I can't think of any other container specific stuff off the top of my head that might be causing the error.

**Comment by Cartache** [comment]
Dear,

For your information, I was facing the same issue. I had to modify my compose file to make it work. By adding:
```
    dns:
      - 1.1.1.1
      - 8.8.8.8
```

**Comment by bwscheller** [comment]
I am also having this issue and have only been able to resolve it by rebooting my docker box.  Rebooting doesn't always resolve the issue.  I have seen it be unable to connect for several days and then have no issues for several weeks.

**Comment by Jolsty** [comment]
Hi I'm having the same problem. Everything worked until I upgrade to the latest version.

**Comment by thrnz** [comment]
The container now explicitly tells curl which dns servers to use, which is needed for the reconnect logic to work. If it's a recent issue then there could be something going wrong there.

There should be something like `curl options: --interface 172.16.29.2 --dns-interface eth0 --dns-servers 127.0.0.11 --local-port 12300-12310` in the logs. I don't suppose there's anything missing or obviously wrong there?

Does running `nslookup google.com` inside the container work, and does the server used match that from the log message?

Does it work with `FIREWALL=0` set?

The script picks the first nameserver listed in `resolv.conf` to use, so I wonder if that might be relevant, or if it could be improved to handle cases where there may be more than one.

**Comment by Jolsty** [comment]
Somehow it has fixed itself after a few restarts.

**Comment by Kirk-Capt** [comment]
none of the above worked for me. I can ping google inside container. nslookup finds serverlist.piaservers.net 
switching to :testing worked

hope that helps

**Comment by thrnz** [comment]
Keep an eye on #147. An Alpine package update from a few days ago was included in the build earlier today, and it broke the way the script was handling dns lookups.
